// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvozIXoiFZ7ScSGPX7w_Q3lLe9ZvJ6OjI',
    appId: '1:904631524025:web:a25530c9948ccb918d5968',
    messagingSenderId: '904631524025',
    projectId: 'movie-mate-b4717',
    authDomain: 'movie-mate-b4717.firebaseapp.com',
    storageBucket: 'movie-mate-b4717.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvLDFOyK_9htCkJCeS-K0rruOg3NQM0yw',
    appId: '1:904631524025:android:c1e9de18a04e57608d5968',
    messagingSenderId: '904631524025',
    projectId: 'movie-mate-b4717',
    storageBucket: 'movie-mate-b4717.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn81gD7irYAY4DXnJdJRl7H3dqX1cXvxs',
    appId: '1:904631524025:ios:394c0fca10005bea8d5968',
    messagingSenderId: '904631524025',
    projectId: 'movie-mate-b4717',
    storageBucket: 'movie-mate-b4717.firebasestorage.app',
    iosBundleId: 'com.example.imdbclone',
  );
}
